/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../lib/jni.h"
/* Header for class test_StringJni */

#ifndef _Included_CommUtils
#define _Included_CommUtils
#ifdef __cplusplus
extern "C" {
#endif
// 由于jvm和c++对中文的编码不一样，因此需要转码。 utf8/16转换成gb2312
char* jstringToChar(JNIEnv *env, jstring jstr) ;

// 由于jvm和c++对中文的编码不一样，因此需要转码。gb2312转换成utf8/16
jstring charTojstring(JNIEnv* env, const char* str);
#ifdef __cplusplus
}
#endif
#endif