/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_StringJni */

#ifndef _Included_test_StringJni
#define _Included_test_StringJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_StringJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_StringJni_get
  (JNIEnv *, jclass);

/*
 * Class:     test_StringJni
 * Method:    setStudent
 * Signature: (Ltest/Student;)Ltest/Student;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_setStudent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     test_StringJni
 * Method:    getStudent
 * Signature: ()Ltest/Student;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_getStudent__
  (JNIEnv *, jobject);

/*
 * Class:     test_StringJni
 * Method:    getStudent
 * Signature: (ILjava/lang/String;)Ltest/Student;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_getStudent__ILjava_lang_String_2
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     test_StringJni
 * Method:    sumAge
 * Signature: (Ltest/Student;Ltest/Student;)I
 */
JNIEXPORT jint JNICALL Java_test_StringJni_sumAge
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     test_StringJni
 * Method:    createStudent
 * Signature: ([I[Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_createStudent
  (JNIEnv *, jobject, jintArray, jobjectArray);

/*
 * Class:     test_StringJni
 * Method:    getFirstStudent
 * Signature: (Ljava/util/ArrayList;)Ltest/Student;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_getFirstStudent__Ljava_util_ArrayList_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     test_StringJni
 * Method:    getFirstStudent
 * Signature: ([Ltest/Student;)Ltest/Student;
 */
JNIEXPORT jobject JNICALL Java_test_StringJni_getFirstStudent___3Ltest_Student_2
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
